default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: krishna
  password: Krishna@501

development:
  <<: *default
  database: bazaar_development

test:
  <<: *default
  database: bazaar_test

production:
  <<: *default
  database: bazaar_production
  username: bazaar
  password: <%= ENV['BAZAAR_DATABASE_PASSWORD'] %>
